### ISSUE TITLE
Content Subdirectories

### ISSUE THREAD

**Issue by curtisault** [Worble/Zulma#6]
I'd like to organize my content by creating sub directories under the content directory.

e.g. posts about rust `content/rust` or posts about javascript `content/js`

These posts are searchable but they don't show up on the home page automatically. How do I get them to show up on the home page? I don't mind adding it manually, but I don't know where to add that reference.

**Comment by Worble** [comment]
From Zola's documentation: https://www.getzola.org/documentation/content/section/
Under your folder, create an `_index.md` file you haven't already. In the front-matter (i.e in between an opening and closing +++) put `transparent = true` like this:

```
+++
transparent = true
+++
```
in: `content/subfolder/_index.md`

Posts under these folders should now show up on the home page.

**Comment by curtisault** [comment]
That did the trick. Thanks!
