### ISSUE TITLE
Security Vulnerabilities Detected

### ISSUE THREAD

**Issue by michael-conrad** [Worble/Zulma#7]
Just installed the theme in a new site and I am getting from github:

```
acorn moderate severity by GitHub
themes/Zulma/javascript/yarn.lock

minimist moderate severity by GitHub
themes/Zulma/javascript/yarn.lock

serialize-javascript moderate severity by GitHub
themes/Zulma/javascript/yarn.lock 
```

https://github.com/CherokeeLanguage/CherokeeLessons.com/network/alerts

**Comment by Worble** [comment]
These are pretty much all downstream from webpack and webpack-cli. It's potentially possible to fix some of these by manually editing the lock file, however all JavaScript dependencies in Zulma are dev ones that are just used for transforming and bundling the code, none of these vulnerabilities (should) ever hit a users browser, so I'd rather wait than go knee-deep into the lock file. Of course I'm always open to PR's if you want to try this yourself.

**Comment by michael-conrad** [comment]
How about adding to the instructions for which dev only files or folders
are safe to remove as a clear step for non-devs to follow? As an end user I
only need the compiled output, not the entire compile chain in my project.

**Comment by Worble** [comment]
Sure, I'll update the readme with that info. In the meantime feel free to delete the folder just called `javascript` at the top level, that should clear up the warnings.
